Tests for developed featues
petmetic/watering_schedule pull request #26
Opened 2024-04-19 08:25 UTC by petmetic

Writing tests for all features that are currently developed using Vitest testing library

2024-04-23 20:56 UTC, jurecuhalev commented
Test title doesn't reflect PR contents

2024-04-23 20:56 UTC, jurecuhalev requested changes
PR title doesn't accurately reflect contents of this PR

2024-04-24 07:10 UTC, simonfabcic approved these changes
As much as I know, it looks OK...

2024-04-26 08:12 UTC, jurecuhalev approved these changes

2024-04-26 11:23 UTC, merged